[[plugins]]
package = "netlify-plugin-cache"
  [plugins.inputs]
  paths = ["static/assets/images/", "static/assets/socials/"]

[[headers]]
  for = "*.avif"
    [headers.values]
      Content-Type = "image/avif"
      Content-Disposition = "inline"
